app/models.py
# app/models.py

from app import db
from sqlalchemy import Column, DateTime
from datetime import datetime



class Blog(db.Model):

    __tablename__ = "articles"

    id = db.Column(db.Integer, primary_key=True)
    article_title = db.Column(db.String, nullable=False)
    article_author = db.Column(db.String, nullable=False)
    pub_date = db.Column(DateTime, default=datetime.utcnow)
    article_content = db.Column(db.String, nullable=False)

    def __init__(self, title, author, content):
        self.article_title = title
        self.article_author = author
        self.article_content = content

    def __repr__(self):
        return 'title {}'.format(self.name)



class User(db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String, unique=True, nullable=False)
    first_name = db.Column(db.String, nullable=False)
    last_name = db.Column(db.String, nullable=True)
    email = db.Column(db.String, unique=True, nullable=False)
    password_plaintext = db.Column(db.String, nullable=False) ######TEMPORARY -- MUST HASH THE PASSWORD AND DELETE

    def __init__(self, username, first_name, last_name, email, password_plaintext):
        self.username = username
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.password_plaintext = password_plaintext

    def __repr__(self):
        return '<User {0}>'.format(self.name)
    

app/blog/forms.py
# app/blog/forms.py

from flask_wtf import Form
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired



class AddArticleForm(Form):
    article_title = StringField('Article Title', validators=[DataRequired()])
    article_author = StringField('Article Author', validators=[DataRequired()])
    article_content = TextAreaField('Article Content', validators=[DataRequired()])

app/users/forms.py
# app/users/forms.py


from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField
from wtforms.validators import DataRequired, Length, EqualTo, Email



class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=6, max=40)])
    first_name = StringField('First Name', validators=[DataRequired(), Length(min=2, max=40)])
    last_name = StringField('Last Name', validators=None)
    email = StringField('Email', validators=[DataRequired(), Email(), Length(min=6, max=40)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=40)])
    confirm = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])

app/__init__.py
######################## Imports ########################
from flask import Flask
from flask_sqlalchemy import SQLAlchemy



######################## Config ########################

app = Flask(__name__, instance_relative_config=True)
app.config.from_pyfile('flask.cfg')

db = SQLAlchemy(app)



######################## Blueprints ########################

from app.users.views import users_blueprint
from app.blog.views import blog_blueprint
from app.portfolio.views import portfolio_blueprint

# Register the blueprints
app.register_blueprint(users_blueprint)
app.register_blueprint(blog_blueprint)
app.register_blueprint(portfolio_blueprint)

app/blog/views.py
# app/blog/views.py

#################### Imports ####################

from flask import render_template, Blueprint, request, redirect, url_for, flash
from app import app
from app import db
from app.models import Blog
from .forms import AddArticleForm



#################### Config ####################

blog_blueprint = Blueprint('blog', __name__, template_folder='templates')



#################### Helper Functions ####################

def flash_errors(form):
    for field, errors in form.errors.items():
        for error in errors:
            flash(u"Error in the %s field - %s" % (
                getattr(form, field).label.text,
                error
            ), 'info')



#################### Routes ####################

@blog_blueprint.route('/')
@blog_blueprint.route('/index')
@blog_blueprint.route('/blog')
def index():
    all_articles = Blog.query.all()
    return render_template('blog.html', articles=all_articles)

@blog_blueprint.route('/add_article', methods=['GET', 'POST'])
def add_article():
    form = AddArticleForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            new_article = Blog(form.article_title.data, form.article_author.data, form.article_content.data)
            db.session.add(new_article)
            db.session.commit()
            flash('New Article, {}, added!'.format(new_article.article_title), 'success')
            return redirect(url_for('blog.index'))
        else:
            flash_errors(form)
            flash('ERROR! Article was not added.', 'error')

    return render_template('add_article.html', form=form)

app/portfolio/views.py
# app/users/views.py

#################### Imports ####################

from flask import render_template, Blueprint



#################### Config ####################

portfolio_blueprint = Blueprint('portfolio', __name__, template_folder='templates')



#################### Routes ####################

@portfolio_blueprint.route('/portfolio')
def portfolio():
    return render_template('portfolio.html')

app/users/views.py
# app/users/views.py
 
#################### Imports ####################

from flask import render_template, Blueprint, request, redirect, url_for, flash
from sqlalchemy.exc import IntegrityError

from .forms import RegisterForm
from app import db
from app.models import User


#################### Config ####################

users_blueprint = Blueprint('users', __name__, template_folder='templates')



#################### Routes ####################

@users_blueprint.route('/login')
def login():
    return render_template('login.html')

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                new_user = User(form.username.data, form.first_name.data, form.last_name.data, form.email.data, form.password.data)
                new_user.authenticated = True
                db.session.add(new_user)
                db.session.commit()
                flash('Thank you for registering!', 'success')
                return redirect(url_for('blog.index'))
            except IntegrityError:
                db.session.rollback()
                flash('ERROR! Email ({}) already exists.'.format(form.email.data), 'error')
    return render_template('register.html', form=form)

app/views.py
from flask import render_template
from app import app

@app.route('/')
@app.route('/index')
def index():
    user = {'nickname': 'Weldon'} # fake user
    posts = [
        {'author': {'nickname': 'Weldon'},
         'blog_title': {'post_name': 'Example Post 1'},
         'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ligula lectus, gravida et mauris consequat, condimentum eleifend nibh. Cras rhoncus ante eu nunc dictum lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae ultricies urna. Morbi ornare tristique finibus. Maecenas ut egestas purus, in maximus libero. Maecenas sed velit tincidunt, tempor mauris id, aliquam turpis. Quisque id arcu sed arcu lacinia aliquam. Integer laoreet ipsum diam, dignissim viverra libero tincidunt sit amet. Sed euismod neque quis tellus porta, bibendum ornare urna convallis. Vivamus sollicitudin sollicitudin leo eu elementum.'
        },
        {'author': {'nickname': 'Brandy'},
         'blog_title': {'post_name': 'Example Post 2'},
         'body': 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis ligula lectus, gravida et mauris consequat, condimentum eleifend nibh. Cras rhoncus ante eu nunc dictum lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer vitae ultricies urna. Morbi ornare tristique finibus. Maecenas ut egestas purus, in maximus libero. Maecenas sed velit tincidunt, tempor mauris id, aliquam turpis. Quisque id arcu sed arcu lacinia aliquam. Integer laoreet ipsum diam, dignissim viverra libero tincidunt sit amet. Sed euismod neque quis tellus porta, bibendum ornare urna convallis. Vivamus sollicitudin sollicitudin leo eu elementum.'
        }
    ]
    return render_template('index.html', title='Home', user=user, posts=posts)

app/templates/_form_macros.html
<!-- app/blog/templates/_form_macros.html -->

{% macro render_field(field) %}


<dt>{{ field.label }}:

<dd> {{ field(**kwargs) | safe }}
    {% if field.errors %}
        <span class="error">
            {% for error in field.errors %}
                {{ error }}
            {% endfor %}
        </span>
    {% endif %}
</dd>

{% endmacro %}

app/templates/add_article.html
{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}

{% block content %}


<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-3 text-center">Add Article</h1>
    </div>
</div>

<div class="col-sm-12 col-md-8 mx-auto">
    <form action="{{ url_for('blog.add_article') }}" method="post">
        {{ form.csrf_token }}
        <div class="container">
            <dl>
                {{ render_field(form.article_title, placeholder="Article Title", style="width: 100%") }}
                {{ render_field(form.article_author, placeholder="Article Author", style="width: 100%") }}
                {{ render_field(form.article_content, placeholder="Article Content", style="width: 100%") }}
            </dl>
            <div class="col-xl-5 mx-auto">
                <button class="btn btn-sm btn-success btn-block" type="submit">Add Article</button>
                <button class="btn btn-sm btn-warning btn-block" type="reset">Reset</button>
            </div>
        </div>
    </form>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="description" content="Weldon's Blog and Portfolio">
    <meta name="author" content="Weldon Malbrough">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}"> -->

    {% if title %}
    <title> {{ title }} - Weldon's Blog </title>
    {% else %}
    <title>Welcome to Weldon's Blog</title>
    {% endif %}
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand text-success" href="/index">MALBWA</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item"><a class="nav-link text-success" href="/blog">Blog</a></li>
                    <li class="nav-item"><a class="nav-link text-success" href="/portfolio">Portfolio</a></li>
                    <li class="nav-item"><a class="nav-link text-success" href="/about">About</a></li>
                    <li class="nav-item"><a class="nav-link text-success" href="/contact">Contact</a></li>
                    <li class="nav-item"><a class="nav-link text-success" href="{{ url_for('blog.add_article') }}">Add Article</a></li>
                    {# <li class="nav-item"><a class="nav-link text-success" href="/register">Register</a></li> #}
                    <li class="nav-item"><a class="nav-link text-success" href="{{ url_for('users.register') }}">Register</a></li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="text" placeholder="Username" aria-label="Login">
                    <input class="form-control mr-sm-2" type="text" placeholder="Password" aria-label="Login">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">LOGIN</button>
                </form>
            </div>
        </nav>

        <!-- flash messages -->
        {% for error_message in get_flashed_messages(category_filter=["error"]) %}
            <div class="alert alert-danger alert-dismissible">{{ error_message }}</div>
        {% endfor %}
        {% for success_message in get_flashed_messages(category_filter=["success"]) %}
            <div class="alert alert-success alert-dismissible">{{ success_message }}</div>
        {% endfor %}
        {% for info_message in get_flashed_messages(category_filter=["info"]) %}
            <div class="alert alert-info alert-dismissible">{{ info_message }}</div>
        {% endfor %}

        {% block content %}{% endblock %}

    </div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>

app/templates/blog.html
{% extends "base.html" %}
{% block content %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3 text-center">Most Recent Articles</h1>
        </div>
    </div>

    {# <h1>Hello, {{ user.nickname }}! </h1> #}
    {% for article in articles %}

    <div class="container my-3">
        <div class="row">
            <div class="col-sm-8 col-xs-12 mx-auto">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title">
                            {{ article.article_title }}
                        </h3>
                        <p class="card-subtitle mb-2 text-muted">
                            By <a href="#" class="post-author">
                                    {{ article.article_author }}
                                </a> on {{ article.pub_date }}
                        </p>
                        <p class="card-text">
                            {{ article.article_content }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% endfor %}
{% endblock %}

app/templates/login.html
{# app/users/templates/login.html #}

{% extends "base.html" %}
{% block content %}
   <h2> "Future location to login to Weldon's Blog and Portfolio" </h2>
{% endblock %}

app/templates/portfolio.html
{# app/users/templates/login.html #}

{% extends "base.html" %}
{% block content %}
   <h2> "Future location of Weldon's Portfolio" </h2>
{% endblock %}

app/templates/register.html
<!-- app/templates/register.html -->

{% extends "base.html" %}
{% from "_form_macros.html" import render_field %}
 
{% block content %}

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-6 text-center">Please Register Your New Account</h1>
    </div>
</div>



<div class="col-sm-12 col-md-4 mx-auto my-4">
    <form action="{{ url_for('users.register') }}" method="post">
        {{ form.csrf_token }}
        <div class="container">
            <dl>
                {{ render_field(form.username, placeholder="Username", style="width: 100%") }}
                {{ render_field(form.first_name, placeholder="First Name", style="width: 100%") }}
                {{ render_field(form.last_name, placeholder="Last Name", style="width: 100%") }}
                {{ render_field(form.email, placeholder="Email address", style="width: 100%") }}
                {{ render_field(form.password, placeholder="Password", style="width: 100%") }}
                {{ render_field(form.confirm, placeholder="Confirm password", style="width: 100%") }}
            </dl>
        <button class="btn btn-sm btn-success btn-block" type="submit">Create New Account</button>
        <button class="btn btn-sm btn-warning btn-block" type="reset">Reset</button>
        </div>
    </form>
</div>
 
{% endblock %}